language: ruby
os: linux
script:
  - sudo apt-add-repository -y ppa:texlive-backports/ppa
  - sudo apt-get update
  - sudo apt-get -y install texlive-lang-cjk
  - sudo apt-get -y install texlive-latex-recommended texlive-pictures texlive-latex-extra
  - sudo apt-get -y install texlive-fonts-extra
  - sudo apt-get -y install latexmk
  - rake
