CC_FLAGS = '-Os -mmcu=atmega8 -fdata-sections -ffunction-sections -Wl,--gc-sections'
SIZE_FLAGS = '--format=avr --mcu=atmega8'

desc 'コンパイル. -fstack-usageは有り.'
task :default do
  sh "bundle exec sfrp BlinkLED --build='avr-gcc -fstack-usage #{CC_FLAGS}'"
  sh "avr-size #{SIZE_FLAGS} BlinkLED"
end

desc 'インストール'
task :install => :default do
  sh "sudo avrdude -c avrispmkII -P usb -p m8 -U flash:w:BlinkLED:e -v"
end

desc '掃除'
task :clean do
  sh 'rm -rf ./BlinkLED ./KTimerBench ./KTimerBench.sfrp ./output ./*.su'
end

desc 'log解析して評価値を出す'
task 'eval' do
  cd 'evaluation' do
    sh 'ruby ../../evaluator/eval.rb < ./log.txt'
  end
end
